export const ProyectsInfo = [
  {
    name: "NINTENDO CLON",
    info: "Mi primer proyecto en equipo fue el clon de la HomePage de Nintendo.com aprendiendo en ese proceso todos los problemas que HTML y CSS pueden presentar y como solventarlo. Durante ese mes de proyecto además tuve mi primera experiencia a cargo de un equipo (conformado por un servidor y 4 compañeros mas) y puedo decir que fue una experiencia inolvidable que me enseñó lo duro y gratificante que es estar al cargo de algo así. Además durante ese proyecto desarrollé solidas bases sobre como diseñar una aplicación sabiendo componentizar y la importancia de las clases, la herencia y la gestión de un buen código para optimizar la página. Como reto final de este proceso todo el rediseño de responsive estuvo supervisado por mi y, pese a ser mi primer proyecto tuvo un resultado muy agradable en todos los dispositivos.",
    pics : [ "src/assets/nin1.png" , "src/assets/nin2.png" , "src/assets/nin3.png" , "src/assets/nin4.png" , "src/assets/nin5.png" , "src/assets/nin6.png" , "src/assets/nin7.png"]
},
{
    name: "EA UPDATE",
    info: "A penas acabé el anterior proyecto se nos encomendó no solo imitar, si no añadir además nuevas funcionalidades a una web ya existente, y elegimos entre las posibles la de Electronic Arts. Por mi parte en este caso tuve la tarea de desarrollar un componente original desde 0 donde resumiese algún apartado de la web real de forma mas interactiva y fundido con la home, por lo que decidí implementar un slider con parte de la información sobre uno de los servicios de juegos en línea que ofrecen además de un menú lateral donde puedes consultar los distintos planes de suscripción, precios, ventajas de cada uno, etc.  De manera cómoda e intuitiva para que el usuario reciba la máxima información en el menor tiempo y clics posibles. Dados los resultados obtenidos en el proyecto anterior, el equipo confió en mi de nuevo esta vez para el rediseño de la pagina en los diferentes dispositivos y dada la libertad que teníamos pudimos hacer algunos componentes diferentes al original, obteniendo así un resultado muy positivo además del aprendizaje que supone diseñar junto con un equipo algo de manera original por primera vez.",
    pics : [ "src/assets/ea1.png" , "src/assets/ea2.png" , "src/assets/ea3.png" , "src/assets/ea4.png" , "src/assets/ea5.png" , "src/assets/ea6.png", "src/assets/ea7.png", "src/assets/ea8.png"]
},
{
    name: "MUSICONNECT",
    info: "El tercero y último de los proyectos del curso se trató de una web totalmente original. En este caso el equipo me eligió de nuevo como líder por la gestión que realicé en el primer proyecto y mi gran iniciativa a la hora de echar siempre una mano a los demás. Gracias a ello pude reafirmarme en mi creencia de que soy un miembro de equipo total, el cual se crece cuando el equipo va unido y no teme tomar las riendas si es necesario. En este proyecto mi papel, además de organizar y prestar apoyo al resto del equipo, mi trabajo se centró en el desarrollo de todos los componentes cuyo funcionamiento dependía de la base de datos externa. Gracias a ello aprendí la importancia de los componentes dinámicos, como en el caso del header donde una pequeña barra de búsqueda nos daba acceso mediante el nombre que escribiéramos a una serie de usuarios de Spotify (aquellos con perfil publico), el acceso a una lista con los últimos 50 artistas escuchados por el usuario que hiciese logIn, y finalmente la gestión de los datos del usuario que hacía el logIn.  En este caso el framework React/Vite fue vital para el desarrollo de la misma, y pese al reto que fue aprender a usar un framework por primera vez, me dio las herramientas mas que necesarias para la dura tarea que tuve y la suficiente confianza para lanzarme de cabeza a por mi proyecto mas reciente.",
    pics : [ "src/assets/mscn1.png" , "src/assets/mscn2.png" , "src/assets/mscn3.png" , "src/assets/mscn4.png" , "" , ""]
},
{
    name: "AQUASELLA RELOADED",
    info: "Por último (por ahora), este mes de Agosto (2024), junto con un compañero de promoción en DevelHope, decidimos hacer un proyecto independiente durante el verano para fortalecer nuestros conocimientos. Para soltarnos en diferentes entornos decidimos desarrollar la web en NextJS, framework que nos sorprendió gratamente desde el día 1 por la utilidad y complejidad que este aporta al desarrollo en si. En este caso no dejaré capturas si no el link a la página para que sea disfrutada de primera mano. Además de con fines educativos, hemos desarrollado esta página con la intención de mejorar, componentizar y optimizar la web ya existente de Aquasella.com . Este proyecto ha sido sin duda el mas apasionante hasta ahora por haberlo hecho sin ninguna ayuda mas que la de Pablo Diaz, un inestimable socio junto a quien he aprendido más incluso sobre la importancia de un equipo apasionado y talentoso. Los conocimientos sin ambición no son nada y espero que este proyecto que hemos desarrollado mientras buscábamos trabajo, en apenas unas semanas, demuestre la constancia y trabajo de hemos puesto en él.",
    href: "https://aqua-reloaded.vercel.app",
    pics : ["src/assets/aqs2.png", "src/assets/aqs1.png", "src/assets/aqs3.png", "src/assets/aqs4.png", "src/assets/aqs5.png", "src/assets/aqs6.png", "src/assets/aqs7.png", "src/assets/aqs8.png", ]  
},

];
